//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad2D.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.2")]
        public string CameraIP {
            get {
                return ((string)(this["CameraIP"]));
            }
            set {
                this["CameraIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int CameraPort {
            get {
                return ((int)(this["CameraPort"]));
            }
            set {
                this["CameraPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.10")]
        public string PLCIP {
            get {
                return ((string)(this["PLCIP"]));
            }
            set {
                this["PLCIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2004")]
        public int PLCPort {
            get {
                return ((int)(this["PLCPort"]));
            }
            set {
                this["PLCPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1234")]
        public string DefaultPass {
            get {
                return ((string)(this["DefaultPass"]));
            }
            set {
                this["DefaultPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$2a$10$YhtPJ2KYImFOm0lDbRs93u55GO9BhD5w0GPrToJcn2MwhzOx/Hzd.")]
        public string AdminPass {
            get {
                return ((string)(this["AdminPass"]));
            }
            set {
                this["AdminPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("955")]
        public int VelocityMem {
            get {
                return ((int)(this["VelocityMem"]));
            }
            set {
                this["VelocityMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("950")]
        public int PLCInformationMem {
            get {
                return ((int)(this["PLCInformationMem"]));
            }
            set {
                this["PLCInformationMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int VerticalScan {
            get {
                return ((int)(this["VerticalScan"]));
            }
            set {
                this["VerticalScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public int VerticalEdge {
            get {
                return ((int)(this["VerticalEdge"]));
            }
            set {
                this["VerticalEdge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int HorizontalScan {
            get {
                return ((int)(this["HorizontalScan"]));
            }
            set {
                this["HorizontalScan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int HorizontalEdge {
            get {
                return ((int)(this["HorizontalEdge"]));
            }
            set {
                this["HorizontalEdge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ScanAriaSegment {
            get {
                return ((int)(this["ScanAriaSegment"]));
            }
            set {
                this["ScanAriaSegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int VerticalBoundrySegment {
            get {
                return ((int)(this["VerticalBoundrySegment"]));
            }
            set {
                this["VerticalBoundrySegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int HorizonalBoundrySegment {
            get {
                return ((int)(this["HorizonalBoundrySegment"]));
            }
            set {
                this["HorizonalBoundrySegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("960")]
        public int BridgeOptionMem {
            get {
                return ((int)(this["BridgeOptionMem"]));
            }
            set {
                this["BridgeOptionMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("970")]
        public int ClampMem {
            get {
                return ((int)(this["ClampMem"]));
            }
            set {
                this["ClampMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("980")]
        public int XEncoderMem {
            get {
                return ((int)(this["XEncoderMem"]));
            }
            set {
                this["XEncoderMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("984")]
        public int YEncoderMem {
            get {
                return ((int)(this["YEncoderMem"]));
            }
            set {
                this["YEncoderMem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int EdgeMin {
            get {
                return ((int)(this["EdgeMin"]));
            }
            set {
                this["EdgeMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int EdgeMax {
            get {
                return ((int)(this["EdgeMax"]));
            }
            set {
                this["EdgeMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DiskDiameter {
            get {
                return ((int)(this["DiskDiameter"]));
            }
            set {
                this["DiskDiameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("565")]
        public int FocalLinPixels {
            get {
                return ((int)(this["FocalLinPixels"]));
            }
            set {
                this["FocalLinPixels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double ScaleFESize {
            get {
                return ((double)(this["ScaleFESize"]));
            }
            set {
                this["ScaleFESize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int FELimit {
            get {
                return ((int)(this["FELimit"]));
            }
            set {
                this["FELimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("175")]
        public int edgeOffset {
            get {
                return ((int)(this["edgeOffset"]));
            }
            set {
                this["edgeOffset"] = value;
            }
        }
    }
}
